## Docker image: https://hub.docker.com/_/python
image: docker.io/python:3.11

stages:
  - linting
  - generate_documentation

variables:
  # Create a shallow git copy
  GIT_DEPTH: 1

.install_prerequesites_pip: &install_prerequesites_pip |
  pip install -r requirements.txt

.setup_for_html: &setup_for_html |
  apt-get update
  apt-get --yes --no-install-recommends install pandoc

.setup_for_graph: &setup_for_graph |
  #apt-get update
  apt-get --yes --no-install-recommends install gnuplot
  pip install gitpython requests pyyaml
  git fetch --tags origin main

yamllint:
  stage: linting
  allow_failure: yes
  rules:
    - if: $CI_MERGE_REQUEST_ID                      # Execute jobs in merge request context
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH   # Execute jobs when a new commit is pushed to default branch
      when: always
  before_script:
    - *install_prerequesites_pip
  script:
    - yamllint devices.yml

devices_integrity:
  stage: linting
  allow_failure: yes
  rules:
    - if: $CI_MERGE_REQUEST_ID                      # Execute jobs in merge request context
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH   # Execute jobs when a new commit is pushed to default branch
      when: always
  before_script:
    - *install_prerequesites_pip
  script:
    - ./bin/devices-integrity.py > >(tee -a stdout.log) 2> >(tee -a stderr.log >&2)
    - grep -q '[^[:space:]]' stderr.log && exit 1 || exit 0

pages:
  stage: generate_documentation
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH   # Execute jobs when a new commit is pushed to default branch
      when: always
  before_script:
    - *install_prerequesites_pip
    - *setup_for_html
    - *setup_for_graph
  script:
    - mkdir -pv ./public/
    - cp -v ./.gitlab/404.html ./public/
    # <setup_for_graph>
    - ./bin/csv-stats.py | tee ./csv-stats.csv
    - gnuplot ./.gitlab/csv-stats.gnuplot
    - cp -v csv-stats.* ./public/
    # </setup_for_graph>
    # <setup_for_html>
    - ./bin/generate-android-versions.py
    - ./bin/generate-device-kernels.py
    - ./bin/generate-image-models.py
    - ./bin/generate-images.py
    - ./bin/generate-kernels.py
    - cp -v ./.gitlab/public.css ./public/
    - pandoc --standalone ./.gitlab/www.md       --css=public.css --include-in-header=./.gitlab/header.html --output=./public/index.html
    - pandoc --standalone ./android-versions.md  --css=public.css --include-in-header=./.gitlab/header.html --output=./public/android-versions.html
    - pandoc --standalone ./device-kernels.md    --css=public.css --include-in-header=./.gitlab/header.html --output=./public/device-kernels.html
    - pandoc --standalone ./image-models.md      --css=public.css --include-in-header=./.gitlab/header.html --output=./public/image-models.html
    - pandoc --standalone ./images.md            --css=public.css --include-in-header=./.gitlab/header.html --output=./public/images.html
    - pandoc --standalone ./kernels.md           --css=public.css --include-in-header=./.gitlab/header.html --output=./public/kernels.html
    - pandoc --standalone ./.gitlab/csv-stats.md --css=public.css --include-in-header=./.gitlab/header.html --output=./public/csv-stats.html
    - find public/ -type f -name '*.html' -print -exec sed -i -E 's_<table( |>)_<table id="pretty"\1_' {} +
    # </setup_for_html>
  artifacts:
    paths:
      - ./public
    expire_in: 1 week
